version: '3.9'
services:
  #mongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

#node API Container or Service

  api:
    build: .
    ports:
      - 4000:2000
    volumes:
      - .:/usr/src/app
    environment:
      URL: mongodb://mongo_db:27017/
      PORT: 2000
      DB_NAME: kitty
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}